name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Release Please (Generating CHANGELOG.md)
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          version-file: package.json

      - name: Get Release Version
        run: echo "Current Version - ${{ steps.release_please.outputs.tag_name }}"